# Generated by Django 4.2.30 on 2026-07-05 17:47

from django.db import migrations, models
import django.db.models.deletion

CNPJ_EMPRESA_PADRAO = '00000000000000'


def atribuir_empresa_padrao_a_usuarios_existentes(apps, schema_editor):
    """Contas criadas antes deste campo existir (ex: superusers de teste
    criados via createsuperuser) ficariam com empresa=NULL e passariam a
    tomar 403 de todo endpoint de negócio assim que o multi-tenant real
    entrar em vigor. Preserva continuidade apontando pra empresa 'padrão'
    já semeada — mesmo raciocínio das migrations anteriores que sempre
    trataram contas/registros pré-existentes como "ainda usam o padrão"."""
    Usuario = apps.get_model('contas', 'Usuario')
    Empresa = apps.get_model('estoque', 'Empresa')

    empresa_padrao = Empresa.objects.filter(cnpj=CNPJ_EMPRESA_PADRAO).first()
    if empresa_padrao is not None:
        Usuario.objects.filter(empresa__isnull=True).update(empresa=empresa_padrao)


def reverter(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_movimentacao_usuario_obrigatorio'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='estoque.empresa'),
        ),
        migrations.RunPython(atribuir_empresa_padrao_a_usuarios_existentes, reverter),
    ]
