# Generated by Django 4.2.30 on 2026-07-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
