# Generated by Django 4.2.30 on 2026-07-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_categoria_fornecedor_produto_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('REQUISICAO', 'Requisição'), ('DEVOLUCAO', 'Devolução'), ('COMPRA', 'Compra')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotaFiscalCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=44, unique=True)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='estoque.fornecedor')),
            ],
            options={
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscalCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('codigo_produto_fornecedor', models.CharField(blank=True, max_length=60)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('processado', models.BooleanField(default=False)),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='estoque.movimentacao')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.notafiscalcompra')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nfe', to='estoque.produto')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('nota_fiscal', 'numero_item')},
            },
        ),
    ]
