# Generated by Django 4.2.30 on 2026-07-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_movimentacao_tipo_notafiscalcompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
