# Generated by Django 4.2.30 on 2026-07-05 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def semear_configuracao_estoque(apps, schema_editor):
    """Toda empresa precisa de uma ConfiguracaoEstoque (services.obter_estrategia
    depende de `empresa.config_estoque`). Média móvel mantém o comportamento
    já existente antes desta migration."""
    Empresa = apps.get_model('estoque', 'Empresa')
    ConfiguracaoEstoque = apps.get_model('estoque', 'ConfiguracaoEstoque')
    for empresa in Empresa.objects.all():
        ConfiguracaoEstoque.objects.get_or_create(
            empresa=empresa,
            defaults={'metodo_valoracao': 'media_movel', 'regime_tributario': 'simples_nacional'},
        )


def remover_configuracao_estoque(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0008_ledger_saldo_derivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produto',
            name='controla_lote',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='permite_estoque_negativo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saldoestoque',
            name='quantidade_reservada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='solicitante',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=64)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='estoque.produto')),
            ],
            options={
                'unique_together': {('produto', 'numero_lote')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_tributario', models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('mei', 'MEI')], default='simples_nacional', max_length=30)),
                ('metodo_valoracao', models.CharField(choices=[('fifo', 'PEPS / FIFO'), ('media_movel', 'Custo Médio Móvel'), ('custo_padrao', 'Custo Padrão (Standard Cost)')], default='media_movel', max_length=20)),
                ('permite_estoque_negativo', models.BooleanField(default=False)),
                ('controla_lote_por_padrao', models.BooleanField(default=False)),
                ('multi_deposito', models.BooleanField(default=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_estoque', to='estoque.empresa')),
            ],
            options={
                'verbose_name_plural': 'configurações de estoque',
            },
        ),
        migrations.AlterUniqueTogether(
            name='saldoestoque',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.lote'),
        ),
        migrations.AddField(
            model_name='saldoestoque',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.lote'),
        ),
        migrations.AlterUniqueTogether(
            name='saldoestoque',
            unique_together={('produto', 'deposito', 'lote')},
        ),
        migrations.CreateModel(
            name='CamadaCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_original', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_disponivel', models.DecimalField(decimal_places=3, max_digits=14)),
                ('custo_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camadas_custo', to='estoque.deposito')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camadas_custo', to='estoque.lote')),
                ('movimento_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camada_gerada', to='estoque.movimentacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camadas_custo', to='estoque.produto')),
            ],
            options={
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['produto', 'deposito', 'criado_em'], name='estoque_cam_produto_fa7735_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='camadacusto',
            constraint=models.CheckConstraint(check=models.Q(('quantidade_disponivel__gte', 0)), name='camada_saldo_nao_negativo'),
        ),
        migrations.RunPython(semear_configuracao_estoque, remover_configuracao_estoque),
    ]
